server:
  port: 8080

spring:
  application:
    #应用的名称，非必需项。如果不配置，默认使用工程名
    name: timing_food_delivery
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/food_delivery_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username:
      password:
  web:
    resources:
      static-locations: classpath:/backend/, classpath:/front/
#在项目的application.yml中加入redis相关配置
  redis:
    host: localhost # 本地ip或者虚拟机IP。此处使用了本地的
    port: 6379
    password:
    database: 0 # 默认使用0号数据库
  cache:
    redis:
      time-to-live: 1800000  # 设置缓存有效期。非必需，如果没设置就是永久有效

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true # 开启后，表名address_book可以映射为实体类名AddressBook；字段名user_name可以映射为属性名userName
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID    # 主键的生成策略

#文件上传时，上传到指定位置
timing_food_delivery:
  path:

